image: docker:latest

services:
  - docker:dind

stages:
  - docker-build-and-push

docker-create:
  stage: docker-build-and-push
  script:
    - docker build -t registry.gitlab.com/anup.cloud.devops/bms-api .
    - docker push registry.gitlab.com/anup.cloud.devops/bms-api
    
    
