image: docker:latest

services:
  - docker:dind

stages:
  - docker-build
  - docker-push

docker-build:
  stage: docker-build
  script:
    - docker build -t registry.gitlab.com/anup.cloud.devops/bms-api .

docker-push:
  stage: docker-push
  script:
    - docker push registry.gitlab.com/anup.cloud.devops/bms-api
