image: docker:latest

services:
  - docker:dind

stages:
  - docker-build-and-push

before_script:
  - docker login -u $MY_REGISTRY_USER -p $MY_REGISTRY_TOKEN registry.gitlab.com

docker-create:
  stage: docker-build-and-push
  script:
    - docker build -t registry.gitlab.com/$MY_REGISTRY_USER/bms-api:latest .
    - docker push registry.gitlab.com/$MY_REGISTRY_USER/bms-api
    
