apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bms-api
  namespace: bms
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: bms-api
    spec:
      containers:
        - name: bms-api
          image: registry.gitlab.com/anup.cloud.devops/bms-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              protocol: "TCP"
          env:
            - name: MONGO_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bms-api-secrets
                  key: MONGO_DB_PASSWORD
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: bms-api-secrets
                  key: JWT_SECRET_KEY
          