apiVersion: v1
kind: Service
metadata:
  name: bms-api-service
  namespace: bms
  labels:
    name: bms-api
spec:
  selector:
    name: bms-api
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
